# Make sure `**/*` matches zero or more directories, to match files at the root of the glob as well.
glob_matcher: doublestar

output:
  - summary
  - failure

pre-commit:
  parallel: true
  jobs:
    - name: root
      glob: "./{dev,lib}/**/*.{ex,exs,heex}"
      stage_fixed: true
      group:
        parallel: true
        jobs:
          - run: mise exec -- mix format
          - run: mise exec -- mix credo --strict
    - name: demo
      glob: "**/*.{ex,exs,heex}"
      root: demo
      stage_fixed: true
      group:
        parallel: true
        jobs:
          - run: mise exec -- mix format
          - run: mise exec -- mix credo --strict
