defmodule Mix.Tasks.ExtraordinaryUi.Docs.Build do
  @shortdoc "Builds a static Extraordinary UI docs site"
  @moduledoc """
  Builds a static HTML/CSS/JS docs site for Extraordinary UI components.

  Output can be deployed to any static host (GitHub Pages, Netlify, S3, etc)
  without running Phoenix/Elixir on the server.

  ## Options

    * `--output` - output directory (default: `dist/docs`)
    * `--clean` - remove output directory before generating

  ## Examples

      mix extraordinary_ui.docs.build
      mix extraordinary_ui.docs.build --output public/docs --clean
  """

  use Mix.Task

  alias ExtraordinaryUI.Docs.Catalog

  @impl true
  def run(argv) do
    {opts, _, _} =
      OptionParser.parse(argv,
        strict: [
          output: :string,
          clean: :boolean,
          help: :boolean
        ]
      )

    if opts[:help] do
      Mix.shell().info(@moduledoc)
    else
      output_dir = Path.expand(opts[:output] || "dist/docs", File.cwd!())
      clean? = opts[:clean] || false

      if clean? and File.dir?(output_dir), do: File.rm_rf!(output_dir)

      assets_dir = Path.join(output_dir, "assets")
      File.mkdir_p!(assets_dir)

      theme_css = theme_css()
      sections = Catalog.sections()

      File.write!(Path.join(output_dir, "index.html"), page_html(sections, theme_css))
      File.write!(Path.join(assets_dir, "site.js"), site_js())
      File.write!(Path.join(assets_dir, "site.css"), site_css())

      copy_optional_asset(
        "assets/js/extraordinary_ui.js",
        Path.join(assets_dir, "extraordinary_ui.js")
      )

      Mix.shell().info("generated #{relative(output_dir)}")
      Mix.shell().info("entries: #{Catalog.entry_count()}")
      Mix.shell().info("open #{relative(Path.join(output_dir, "index.html"))} in a browser")
    end
  end

  defp copy_optional_asset(source, target) do
    if File.exists?(source) do
      File.cp!(source, target)
      Mix.shell().info("copied #{relative(target)}")
    end
  end

  defp theme_css do
    "assets/css/extraordinary_ui.css"
    |> File.read!()
    |> String.replace(~r/^@import\s+"tailwindcss";\n?/m, "")
    |> String.replace(~r/^@plugin\s+"tailwindcss-animate";\n?/m, "")
  end

  defp page_html(sections, theme_css) do
    """
    <!doctype html>
    <html lang=\"en\" class=\"style-nova\">
      <head>
        <meta charset=\"utf-8\" />
        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />
        <title>Extraordinary UI Docs</title>
        <meta name=\"description\" content=\"Static component docs for Extraordinary UI\" />
        <script src=\"https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4\"></script>
        <style type=\"text/tailwindcss\">
    #{theme_css}

    @layer base {
      body {
        @apply min-h-screen;
      }
    }
        </style>
        <link rel=\"stylesheet\" href=\"./assets/site.css\" />
      </head>
      <body class=\"bg-background text-foreground\">
        <div class=\"mx-auto grid min-h-screen max-w-[1800px] grid-cols-1 lg:grid-cols-[290px_1fr]\">
          <aside class=\"border-border/70 sticky top-0 h-screen overflow-y-auto border-r px-5 py-6\">
            <div class=\"mb-6\">
              <h1 class=\"text-xl font-semibold\">Extraordinary UI</h1>
              <p class=\"text-muted-foreground mt-1 text-sm\">Static component docs</p>
            </div>

            <div class=\"mb-4\">
              <input id=\"component-search\" type=\"search\" placeholder=\"Search components...\" class=\"border-input bg-background h-9 w-full rounded-md border px-3 text-sm\" />
            </div>

            <nav class=\"space-y-4\" aria-label=\"Component sections\">
              #{sidebar_links(sections)}
            </nav>

            <div class=\"mt-6 text-xs text-muted-foreground\">
              Generated by <code>mix extraordinary_ui.docs.build</code>
            </div>
          </aside>

          <main class=\"px-5 py-6 lg:px-8\">
            <section class=\"mb-8\">
              <h2 class=\"text-2xl font-semibold tracking-tight\">Component Library</h2>
              <p class=\"text-muted-foreground mt-2 max-w-3xl text-sm\">
                This page is a static export of all public component functions in Extraordinary UI.
                It can be hosted on any static platform without a Phoenix server.
              </p>
            </section>

            #{sections_html(sections)}
          </main>
        </div>

        <script src=\"./assets/extraordinary_ui.js\"></script>
        <script src=\"./assets/site.js\"></script>
      </body>
    </html>
    """
  end

  defp sidebar_links(sections) do
    Enum.map_join(sections, "\n", fn section ->
      entries =
        Enum.map_join(section.entries, "\n", fn entry ->
          "<li><a class=\"text-muted-foreground hover:text-foreground text-sm\" href=\"##{entry.id}\">#{entry.title}</a></li>"
        end)

      """
      <div>
        <a href=\"##{section.id}\" class=\"text-sm font-semibold\">#{section.title}</a>
        <ul class=\"mt-2 space-y-1\">#{entries}</ul>
      </div>
      """
    end)
  end

  defp sections_html(sections) do
    Enum.map_join(sections, "\n", fn section ->
      entries = Enum.map_join(section.entries, "\n", &entry_html/1)

      """
      <section id=\"#{section.id}\" class=\"mb-12\">
        <h3 class=\"mb-4 text-xl font-semibold\">#{section.title}</h3>
        <div class=\"grid gap-5 xl:grid-cols-2\">#{entries}</div>
      </section>
      """
    end)
  end

  defp entry_html(entry) do
    escaped_preview =
      entry.preview_html |> Phoenix.HTML.html_escape() |> Phoenix.HTML.safe_to_string()

    escaped_docs = entry.docs |> Phoenix.HTML.html_escape() |> Phoenix.HTML.safe_to_string()

    """
    <article id=\"#{entry.id}\" data-component-card data-component-name=\"#{entry.title}\" class=\"rounded-xl border bg-card text-card-foreground shadow-sm\">
      <header class=\"border-border/70 border-b px-4 py-3\">
        <div class=\"flex flex-wrap items-center justify-between gap-2\">
          <h4 class=\"font-medium\"><code>#{entry.module_name}.#{entry.title}/1</code></h4>
          <button type=\"button\" data-copy-preview=\"#{entry.id}\" class=\"inline-flex h-7 items-center rounded-md border px-2 text-xs hover:bg-accent\">Copy HTML</button>
        </div>
        <p class=\"text-muted-foreground mt-2 text-sm\">#{escaped_docs}</p>
      </header>

      <div class=\"p-4\">
        <div class=\"style-nova rounded-lg border bg-background p-4\">#{entry.preview_html}</div>
      </div>

      <details class=\"border-border/70 border-t\">
        <summary class=\"cursor-pointer list-none px-4 py-3 text-sm font-medium\">Rendered HTML</summary>
        <pre class=\"max-h-72 overflow-auto border-t bg-muted/30 p-4 text-xs\"><code id=\"code-#{entry.id}\">#{escaped_preview}</code></pre>
      </details>
    </article>
    """
  end

  defp site_js do
    """
    (() => {
      const searchInput = document.getElementById("component-search")
      const cards = Array.from(document.querySelectorAll("[data-component-card]"))

      const runSearch = () => {
        const query = (searchInput?.value || "").trim().toLowerCase()

        cards.forEach((card) => {
          const name = (card.getAttribute("data-component-name") || "").toLowerCase()
          const visible = !query || name.includes(query)
          card.style.display = visible ? "block" : "none"
        })
      }

      searchInput?.addEventListener("input", runSearch)

      const copyButtons = Array.from(document.querySelectorAll("[data-copy-preview]"))
      copyButtons.forEach((button) => {
        button.addEventListener("click", async () => {
          const id = button.getAttribute("data-copy-preview")
          const code = document.getElementById(`code-${id}`)
          if (!code) return

          const text = code.textContent || ""
          try {
            await navigator.clipboard.writeText(text)
            const original = button.textContent
            button.textContent = "Copied"
            setTimeout(() => {
              button.textContent = original
            }, 1200)
          } catch (_error) {
            // no-op
          }
        })
      })
    })()
    """
  end

  defp site_css do
    """
    :root {
      color-scheme: light;
    }

    html {
      scroll-behavior: smooth;
    }

    summary::-webkit-details-marker {
      display: none;
    }

    summary::after {
      content: "▾";
      float: right;
      color: var(--muted-foreground);
    }

    details[open] summary::after {
      content: "▴";
    }
    """
  end

  defp relative(path), do: Path.relative_to(path, File.cwd!())
end
